name: Copy latest stable release artifacts to the stable dir

on:
  push:

  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure git
        run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"

      - name: Replace content of "stable" with the artifacts of the latest stable release
        run: |
            LATEST_RELEASE=`cat latest_release.txt`
            rm -rf stable/*
            cp -a $LATEST_RELEASE/. stable
            git add .
            git commit -m "Replace stable directory"
            git push
