name: Update stable directory

on: 
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get the latest stable version number
        id: get-latest-version
        run: echo "::set-output name=version::$(cat latest_release.txt)"

      - name: Delete current stable dir
        run: |
          git rm -r stable

      - name: Copy latest stable version content to "stable" directory
        run: |
          mkdir stable
          cp -a ${{ steps.get-latest-version.outputs.version }}/* stable

      - name: Commit and push
        run: |
          git add -A
          git commit -m "Update stable dir"
          git push

